theme: jekyll-theme-minimal
title: Paul Galjan's repo
description: incremental hacks
url:"https://pgaljan.github.io"
baseurl: "/blog"
repository: "pgaljan/blog"
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
